# Generated by Django 5.1.5 on 2025-03-07 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReveiwModel',
            new_name='ReviewModel',
        ),
    ]
