# Generated by Django 5.1.5 on 2025-03-09 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_reviewmodel_comment_date'),
        ('Borrow_Book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrow',
            new_name='Borrow_Book',
        ),
    ]
